/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  configSyncSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "🚀 Getting Started",
      items: [
        "config-sync/getting-started/installation",
        "config-sync/getting-started/motivation",
        "config-sync/getting-started/cli",
        "config-sync/getting-started/admin-gui",
        "config-sync/getting-started/config-types",
        "config-sync/getting-started/workflow",
        "config-sync/getting-started/naming-convention",
        // "dev-docs/usage-information",
      ],
    },
    {
      type: "category",
      collapsed: true,
      label: "⚙️ Configuration",
      items: [
        "config-sync/configuration/introduction",
        "config-sync/configuration/sync-dir",
        "config-sync/configuration/minify",
        "config-sync/configuration/import-on-bootstrap",
        "config-sync/configuration/custom-types",
        "config-sync/configuration/soft",
        "config-sync/configuration/excluded-types",
        "config-sync/configuration/excluded-config",
      ],
    },
    {
      type: "category",
      collapsed: true,
      label: "🔌 API",
      items: [
        "config-sync/api/plugin-config-types",
      ],
    },
    {
      type: "category",
      collapsed: true,
      label: "📦 Upgrading",
      items: [
        "config-sync/upgrading/generic-update",
      ],
    },
  ],
};

module.exports = sidebars;
