/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  configSyncSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "🚀 Getting Started",
      items: [
        "config-sync/getting-started/installation",
        "config-sync/getting-started/motivation",
        "config-sync/getting-started/cli",
        "config-sync/getting-started/admin-gui",
        "config-sync/getting-started/config-types",
        "config-sync/getting-started/workflow",
        "config-sync/getting-started/naming-convention",
        // "dev-docs/usage-information",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "⚙️ Configuration",
      items: [
        "config-sync/configuration/introduction",
        "config-sync/configuration/sync-dir",
        "config-sync/configuration/minify",
        "config-sync/configuration/import-on-bootstrap",
        "config-sync/configuration/custom-types",
        "config-sync/configuration/soft",
        "config-sync/configuration/included-types",
        "config-sync/configuration/excluded-types",
        "config-sync/configuration/included-config",
        "config-sync/configuration/excluded-config",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "📦 API",
      items: [
        "config-sync/api/plugin-config-types",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "♻️ Upgrading",
      items: [
        "config-sync/upgrading/generic-update",
      ],
    },
  ],

  webtoolsSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "🚀 Getting Started",
      items: [
        "webtools/getting-started/installation",
        "webtools/getting-started/usage",
        "webtools/getting-started/url-alias",
        "webtools/getting-started/url-pattern",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "📦 API",
      items: [
        "webtools/api/rest",
        "webtools/api/graphql",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "🔌 Addons",
      items: [
        "webtools/addons/introduction",
        {
          type: "link",
          label: "Sitemap addon",
          href: '/webtools/addons/sitemap',
        },
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "⚙️ Configuration",
      items: [
        "webtools/configuration/introduction",
        "webtools/configuration/default-pattern",
        "webtools/configuration/website-url",
      ],
    },
    // {
    //   type: "category",
    //   collapsed: false,
    //   label: "♻️ Upgrading",
    //   items: [
    //     "webtools/upgrading/generic-update",
    //   ],
    // },
  ],

  webtoolsSitemapSidebar: [
    {
      type: "link",
      label: "⬅️ Back to Webtools Core docs",
      href: "/webtools/addons",
    },
    {
      type: "category",
      collapsed: false,
      label: "🔌 Sitemap addon",
      items: [
        {
          type: "category",
          collapsed: false,
          label: "🚀 Getting Started",
          items: [
            "webtools/addons/sitemap/getting-started/introduction",
            "webtools/addons/sitemap/getting-started/installation",
            "webtools/addons/sitemap/getting-started/usage",
            "webtools/addons/sitemap/getting-started/multilingual",
            "webtools/addons/sitemap/getting-started/sitemap-index",
            "webtools/addons/sitemap/getting-started/robots-txt",
            "webtools/addons/sitemap/getting-started/cli",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "📦 API",
          items: [
            "webtools/addons/sitemap/api/rest",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "⚙️ Settings",
          items: [
            "webtools/addons/sitemap/settings/introduction",
            "webtools/addons/sitemap/settings/hostname",
            "webtools/addons/sitemap/settings/hostname-overrides",
            "webtools/addons/sitemap/settings/exclude-drafts",
            "webtools/addons/sitemap/settings/include-homepage",
            "webtools/addons/sitemap/settings/default-language-url-type",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "🔧 Configuration",
          items: [
            "webtools/addons/sitemap/configuration/introduction",
            "webtools/addons/sitemap/configuration/cron",
            "webtools/addons/sitemap/configuration/limit",
            "webtools/addons/sitemap/configuration/xsl",
            "webtools/addons/sitemap/configuration/auto-generate",
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
